### PR TITLE
!!! FEATURE: Make electronic address types configurable

### LINKED ISSUE #26: Update the service selector with something useful
Currently the selector contains some pretty outdated services:

image

### PR DESCRIPTION
**Pull request by daniellienert**
Fixes: #26

### CODE REVIEW

**Comment by kdambekalns** [comment]
Well, it still contains the outdated stuff; why not remove some cruft, as this is for master? And if needed, users can add it back…

**Review by kdambekalns — APPROVED** [review]
Looks good!

**Comment by daniellienert** [comment]
That what I have planned. Didn't know what people think about it. Afair you haven't forked the package. So this change could go to the minor while the removal can go to the next major

**Comment by daniellienert** [comment]
... in case Someone added his AIM in the last 10 years 😂

**Comment by kdambekalns** [comment]
> Afair you haven't forked the package.

No, it's released independently from Flow & Neos. Complete freedom FTW! 😎

**Pull request merged**
