### PR TITLE
BUGFIX: Avoid migration failure if account has no party

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
This replaces #6 - @kaystrobach

**Comment by kdambekalns** [comment]
:+1: by reading

**Comment by aertmann** [comment]
no fix needed for postgres?

**Comment by kaystrobach** [comment]
I never tested on postgre and just fixed the mysql problem i found ...

----- Originale Nachricht -----
Von: Aske Ertmann notifications@github.com
Gesendet: 28.12.2015 - 06:57
An: neos/party party@noreply.github.com
Betreff: Re: [party] BUGFIX: Avoid migration failure if account has no party (#7)

**Pull request closed without merging**
